name: Single Agent Example - Continuous Integration

on:
  push:
    branches:
      - prod
      - test
      - dev
    paths:
      - "single-agent/**"
  pull_request:
    branches:
      - prod
      - test
      - dev
    paths:
      - "single-agent/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            single-agent/
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: $NODE_VERSION
          cache: "npm"

      - name: Install dependencies, lint, compile, and test
        working-directory: ./single-agent
        run: |
          npm ci
          npm run lint
          npm run compile
          npm test
